baseURL: "https://jeet-g-shah.github.io/" 
title: Jeet Shah
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: /projects/
          weight: 1
            #- name: Courses
            #  url: /courses/
            #  weight: 2
            #- name: Design
            #  url: /design/
            #  weight: 3        
            #- name: Book
            #  url: /b1/
            #  weight: 4
            #- name: Newsletter
            #  url: https://pmichaillat.substack.com
            #  weight: 5

params:
    description: "This website hosts Jeet Shah's research papers, courses taken, curriculum vitae, and contact information."
    author: Jeet Shah
      #googleAnalyticsID: "G-97G4MZ4061"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jeet Shah
          subtitle: "I am a doctoral candidate in physics at the University of Maryland, College Park. I am interested in theoretical condensed matter physics. Specifically, I am interested in quantum spin liquids, quantum dimer models, gauge theories and mixed state phases."
          imageUrl: "/picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Jeet Shah
          buttons:
            - name: Projects
              url: /projects/
            - name: Courses
              url: /courses/
            #- name: Design
            #  url: /design/
            #- name: Book
            #  url: /b1/
            # - name: Newsletter
            #   url: https://pmichaillat.substack.com
            #- name: Tags
            #  url: /tags/
            #- name: Archive
            #  url: /archive/

    socialIcons:
        - name: CV
          url: /cv.pdf
        - name: Email
          url: mailto:jeet@umd.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=kXIIyhsAAAAJ&hl=en
        - name: Linkedin
          url: https://www.linkedin.com/in/jeet-shah-19b679193/
        - name: arXiv
          url: https://arxiv.org/search/?searchtype=author&query=Jeet+Shah
        #- name: GitHub
        #  url: https://github.com/pmichaillat

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Jeet Shah"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
